
services:
  mysql:
    image: mysql:8.0
    container_name: bravo-mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bravo_db 
      MYSQL_USER: dotnet
      MYSQL_PASSWORD: bravo    
    ports:
      - "3307:3306" # Usamos 3307 para evitar conflictos
    volumes:
      - bravo-mysql-data:/var/lib/mysql
    networks:
      - bravo_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bravo-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    networks:
      - bravo_net

volumes:
  bravo-mysql-data:

networks:
  bravo_net: